### ISSUE TITLE
User Guide Missing

### ISSUE THREAD

**Issue by rolandh15** [openjamoses/EMU-IOT#1]
i wish to use your IOT simulator, in order to write my master thesis, but i find it difficult to get started with the project. Would it be possible to get a minimal version?

**Comment by openjamoses** [comment]
Hello sorry to get back to you a bit late, 
Where you able to get started with the projects?
I should be able to update the documentation soon,

**Comment by rolandh15** [comment]
I had to discontinue my thesis for now, but was not able to get up to date without any docs.
